### ISSUE TITLE
params bug in evaluation_method.py

### ISSUE THREAD

**Issue by z-jiaming** [LingyiHongfd/lvos-evaluation#1]
https://github.com/LingyiHongfd/lvos-evaluation/blob/c05a4c5e5836c1e5488081a124fb32c69c9a30fc/evaluation_method.py#L53
dataset_eval = LVOSEvaluation(llvos_root=args.lvos_path, task=args.task, gt_set=args.set)

it should be lvos_root=args.lvos_path

**Comment by z-jiaming** [comment]
https://github.com/LingyiHongfd/lvos-evaluation/blob/c05a4c5e5836c1e5488081a124fb32c69c9a30fc/lvos/lvos_seperate.py#L41
Due to this evalution is only for val split, it perhaps should be valid_meta.json?


And, following davis2017-evaluation, so i set default_lvos_path to LVOS path, not valid split path.
But, i could run this toolkit well when i set it to valid split path. Personally, I feel that it may be better to modify the settings here, or remind others in the README, and we could set args.mp_nums?

**Comment by LingyiHongfd** [comment]
Thank you for identifying the bug! We have modified the code and update the README. 
For args.mp_nums, it is about whether calculate the score in a multiprocessing manner. You can just set is as 1 in a serial mode. Or set it larger than 1 to speed up. We suggest to set it less than 8 on a regular sever. 
Thanks again for your advice. Feel free to raise question if you have any doubt about LVOS.
