### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by z-jiaming** [LingyiHongfd/lvos-evaluation#2]
https://github.com/LingyiHongfd/lvos-evaluation/blob/bfaa15654811af49a69980f79d5bc3cc6fb4b3e9/lvos/lvos_seperate.py#L11

Here, the SUBSET_OPTIONS should be ['valid', 'test'], because the default args.set is valid.

But after i fix it, and run code with mp=6, the code returns the following error.

![Snipaste_2022-11-28_10-11-59](https://user-images.githubusercontent.com/42411674/204177975-aa5e08c2-9a7e-489c-8e33-6033041f0e29.png)

For the 2nd run, I add print(metrics_res.keys()) at line 58 in evaluation_method.py.
I'm confused that it looks like metrics_res is a str?

**Comment by LingyiHongfd** [comment]
Sorry, it's my fault to forget to update the corresponding file. I have fixed and updated lvos_seperate.py and evaluation_mp.py. I have run the code on my own server in both single and multiple process manner, and the two manners got the same and right result. Thanks for your issue.
