### ISSUE TITLE
Have you finetuned the AOT-T?

### ISSUE THREAD

**Issue by junbao-zhou** [LingyiHongfd/lvos-evaluation#3]
Is the evaluation results of AOT-T generated by the checkpoint on https://github.com/yoxu515/aot-benchmark or the model finetuned on LVOS ?

**Comment by LingyiHongfd** [comment]
Hi, thanks for your interest. I'm sorry it's been so long so I've forgotten some specifics. Maybe the result is the prediction of AOT-T with the origin checkpoint provided by AOT. Please feel free to contact me through Github issue or email if you have any question. Thanks a lot for your interest again.

**Comment by junbao-zhou** [comment]
Thank you for your reply, I will evaluate it myself.
